trentm/python-markdown2

README.md

When doing markdowner = Markdown() we should do from markdown2 import Markdown, otherwise it gives NameError : "Markdown" name is not defined. Thanks You.

Fixes of Quick Usage in README

---

README.md

I changed the link towards the first Python implementation of Markdown. That project moved to PyPI and its home is now at PythonHosted.org.

Python Markdown moved to PyPI and to PythonHosted

---

TODO.txt

I added `markdown-in-html` to the [Extras wiki page](https://github.com/trentm/python-markdown2/wiki/Extras) and also created the [`markdown-in-html`](https://github.com/trentm/python-markdown2/wiki/markdown-in-html) page. Removing this item from the TODO list.

Added markdown-in-html extra to Wiki.

---

lib/markdown2.py
test/tm-cases/tables.html
test/tm-cases/tables.text

This change allows for empty cells in tables when using the 'tables' extra. Given an input like 
> \| K        \| d_Src        \| Function         \| d_Dst         \| Jmp Cmd         \| Jmp_Dest        \| Jmp Test \|
> \| -------- \| ------------ \| ---------------- \| ------------- \| --------------- \| --------------- \| -------- \|
> \|          \| \`src\`        \| \`ps\`             \|               \|                 \|                 \|          \|
The trim's replaced in this pull request would greedily consume all of the spaces and |'s leaving only two cells instead of seven, and cells end up moved the left side, something like this:
> | K        | d_Src        | Function         | d_Dst         | Jmp Cmd         | Jmp_Dest        | Jmp Test |
> | -------- | ------------ | …

Allow empty table cells

---

lib/markdown2.py
test/tm-cases/fenced_code_blocks_leading_paragraph.html
test/tm-cases/fenced_code_blocks_leading_paragraph.opts
test/tm-cases/fenced_code_blocks_leading_paragraph.tags
test/tm-cases/fenced_code_blocks_leading_paragraph.text

Hi, I met a problem when I want to convert my article written by others markdown editor like [Dillinger](http://dillinger.io/).
The problem in code block.
The input:
<pre>
This is python code.
```python
import os
print(os.listdir('.'))
```
</pre>
The output:
```
<p>This is python code.
<code>python
import os
print(os.listdir('.'))
</code></p>
```
But expected output is this:
```
<p>This is python code.</p>
<pre><code>import os
print(os.listdir('.'))
</code></pre>
```
I think most markdown editor suppor this, but markdown2 don't.
So I try to support this.
I have add some test, and all others test has been pass.

Add a case: leading paragraph in fenced_code_blocks.

---

lib/markdown2.py
test/tm-cases/metadata2.html
test/tm-cases/metadata2.metadata
test/tm-cases/metadata2.opts
test/tm-cases/metadata2.tags
test/tm-cases/metadata2.text

`Markdown` package supports parsing metadata without mandatory "---"-wrapping. The fix enables to write metadata like this:
some: metadata
other: stuff
so the top metadata can be separated by a single blank line.

make metadata fences optional

---

lib/markdown2.py
test/tm-cases/numbering.html
test/tm-cases/numbering.opts
test/tm-cases/numbering.text

Numbering is described in the docstring for the _do_numbering method.
A generic numbering capability which can be used for equations,
figures, tables etc.  Could also be used for footnotes if required.  Still in design mode so looking for comments.

Added Numbering

---

lib/markdown2.py
test/tm-cases/metadata.metadata
test/tm-cases/metadata.text
test/tm-cases/metadata2.metadata
test/tm-cases/metadata2.text

This is a fix for #223 
So now you can specify metadata values in an  idented block prefixed by ">". For example:
```
---
test: abc
this-is : a hyphen test
leading~space	: is okay 
And: some, cvs, data, which, you, must, parse, yourself
empty   :
and some: >
long value
that goes multiline
another: example
---
This should be parsed as before
```

Metadata in blocks

---

lib/markdown2.py

I rearranged the list of extras to be alphabetical, to most closely much the Wiki page "Extras". I also added a couple of extras that were missing, namely the `tag-friendly` and `use-file-vars`.

Rearranged extras alphabetically and added some missing ones.

---

.travis.yml
lib/markdown2.py
test/tm-cases/basic_safe_mode.html
test/tm-cases/basic_safe_mode.text
test/tm-cases/inline_links.html
test/tm-cases/link_defn_spaces_in_url.html
test/tm-cases/long_link.html
test/tm-cases/xss_quotes.html

Related to #51 and #174.
When `safe_mode` is truthy, only allows `http`, `https`, and `ftp` protocols in links to prevent XSS.

restrict link protocols in safe mode

---

lib/markdown2.py
test/tm-cases/task_list.html

Currently, the task-list-wrapper-text is:
`_task_list_warpper_str = r'<p><input type="checkbox" class="task-list-item-checkbox" %sdisabled>%s</p>'`. In my opinion, the `<p>` tag is unnecessary.
I think the better option will be:
`<input type="checkbox" class="task-list-item-checkbox" disabled> %s`, as github also handles in this way.
I also have a simple comment on that PR: <https://github.com/trentm/python-markdown2/pull/218/files#r100302342>

improve taks_list extra wrapper html

---

.travis.yml
setup.py
tox.ini

This updates both the tests, and the meta-data in `setup.py` to include versions up to the newest release of Python, version 3.6.

Test on Python 3 versions up to 3.6

---

lib/markdown2.py
test/tm-cases/link_nofollow.html
test/tm-cases/link_nofollow.text
test/tm-cases/link_with_blank.html
test/tm-cases/link_with_blank.text

When you have both `target-blank-lines` and `footnotes` extras enabled, the footnotes unexpectedly open in new tabs.
The proposed solution is to make both `target-blank-lines` and `nofollow` extras ignores links that are just a fragment, eg: `#section1`.
The pull request includes updates to the tests.

Don't let "target-blank-lines" break footnotes

---

lib/markdown2.py
test/tm-cases/tables.html
test/tm-cases/tables.text

Fixes #169
The table extension was missing pipe escaping: so, token `\|` inside table
must not be treated as a separator. That is how GFM does that.
* Original behaviour was to simply split on pipe character; changed to
regex to match only pipes without backslash before them.
* Afterwards, all escaped pipes (`\|`) are changed to single pipes (`|`).
* Added test for table with escaped pipes.

Add pipe escaping in table extension

---

.travis.yml

Drop Python 3.2 support, as many packages no longer support it.

Drop Python 3.2 support

---

lib/markdown2.py
test/tm-cases/metadata.html
test/tm-cases/metadata.text
test/tm-cases/metadata2.html
test/tm-cases/metadata2.text

When parsing the metadata key-value pairs, it incorrectly searches the entire text instead of the metadata header.
For example, 
```python
content = """---
Foo: bar
---
This is a test:
"""
md = markdown2.Markdown(extras=['metadata'])
md.convert(content)
print(md.metadata)
```
results in  `{'Foo': 'bar', 'test': ''}` while it should return only `{'Foo': 'bar'}`

Search for items only within metadata header

---

lib/markdown2.py
test/tm-cases/highlightjs_lang.html
test/tm-cases/highlightjs_lang.opts
test/tm-cases/highlightjs_lang.tags
test/tm-cases/highlightjs_lang.text

I prefer *highlightjs* over *pygments* (and I think *highlightjs* is popular enough to warrant adding this support). Generally *highlightjs* is pretty good about auto-detecting the language used in a codeblock, but sometimes it just doesn't work.
In pure `html` one can do something like:
```html
<pre><code class="cpp"> .... </pre></code>
```
*html-classes* doesn't really work since that specifies the class for all codeblocks (can't have different language codeblocks in the same markdown document).
I added a new extra, *highlightjs-lang* which just uses the existing code to extract the language specified for a (fenced) codeblock.

Add support for highlightjs language class naming in fenced-code-blocks

---

lib/markdown2.py

For FIPS[0] related installation, the MD5 modules are unavailable, to
the tune of md5() raising an exception.  Using sha256() from the same
hashlib passes the same `make test` and is now FIPS compliant.
[0] http://csrc.nist.gov/groups/STM/cmvp/documents/140-1/140val-all.htm

Replace md5() with sha256() for hashing

---

lib/markdown2.py
test/tm-cases/ampersands.html
test/tm-cases/ampersands.tags
test/tm-cases/ampersands.text

- Try to normalize replacements of amps by using the same regex for some of the substitutions.
- Add test file for ampersand issues
TODO: Should try to write a single sub function to use everywhere at some point.
fixes #271 #272

Fix for double amp replacement inside link title

---

lib/markdown2.py

Refs #280 #279 
Prepend toc_html structure to markdown output when using as CLI.

TOC via CLI  toc_html prepended to output

---

lib/markdown2.py
test/tm-cases/fenced_code_blocks_leading_lang_space.tags
test/tm-cases/link_safe_urls.html
test/tm-cases/link_safe_urls.opts
test/tm-cases/link_safe_urls.tags
test/tm-cases/link_safe_urls.text

This PR fixes the following:
```
>>> markdown('[text](#anchor)')
u'<p><a href="#anchor">text</a></p>\n'
>>> markdown('[text](#anchor)', safe_mode='escape')
u'<p><a href="#">text</a></p>\n'
```
In other words - internal anchors should not be considered unsafe.
Also I've added `pygments` tag to `fenced_code_blocks_leading_lang_space` test because it fails without pygments installed.

Do not remove anchors in safe_mode

---

lib/markdown2.py
test/tm-cases/cuddled_para_and_list.html
test/tm-cases/cuddled_para_and_list.text

this hotfix is mainly the resolution of 
https://github.com/trentm/python-markdown2/issues/286

fixing  `cuddled-lists` with a single list item

---

test/test.py
test/testlib.py

According to the Python document, `logging.Logger.warn` is deprecated and not recommended to use:
https://docs.python.org/3.7/library/logging.html#logging.Logger.warning

 Replace a deprecated method

---

lib/markdown2.py

In Python 3.6, I encountered the following warning messages with `markdown2-2.3.5` when I running test cases in my project:
```
markdown2.py:427: DeprecationWarning: invalid escape sequence \S
_key_val_pat = re.compile("[\S\w]+\s*:(?! >)[ \t]*.*\n?", re.MULTILINE)
markdown2.py:432: DeprecationWarning: invalid escape sequence \s
"(.*:\s+>\n\s+[\S\s]+?)(?=\n\w+\s*:\s*\w+\n|\Z)", re.MULTILINE)
markdown2.py:985: DeprecationWarning: invalid escape sequence \|
trim_bar_re = '^\||\|$'
markdown2.py:986: DeprecationWarning: invalid escape sequence \|
split_bar_re = '^\||(?<!\\\\)\|'
markdown2.py:987: DeprecationWarning: invalid escape sequence \|
escape_bar_re = '\\\\\|'
```
These warnings can be avoid by using raw strings.

DeprecationWarning: invalid escape sequence

---

test/testall.py
tools/which.py

In Python 3, `make test` failed because of syntaxes not compatible with Python 3.
This PR fixes these errors with remain Python 2 compatibility.

Fix "make test" in Python 3

---

lib/markdown2.py
test/tm-cases/CVE-2018-5773.html
test/tm-cases/CVE-2018-5773.opts
test/tm-cases/CVE-2018-5773.text
test/tm-cases/basic_safe_mode.html

Add sanitization for incomplete HTML tags.
I believe this PR fix #285 (CVE-2018-5773) as follows:
```pycon
>>> mark('<img src= onerror=alert(/XSS/)>', safe_mode=True)
<p>[HTML_REMOVED]</p>
>>> mark('<img src= onerror=alert(/XSS/) ', safe_mode=True)
<p>&lt;img src="" onerror=alert(/XSS/) </p>
>>> mark('<img src="" onerror=alert(/XSS/)>', safe_mode="escape")
<p>&lt;img src="" onerror=alert(/XSS/)&gt;</p>
>>> mark('<img src="" onerror=alert(/XSS/) ', safe_mode="escape")
<p>&lt;img src="" onerror=alert(/XSS/) </p>
```

Fix CVE-2018-5773: #285

---

README.md
lib/markdown2.py
setup.py
test/test_markdown2.py
test/testall.py
test/testlib.py

Related to Issue #305
This PR remove or replace source code for support legacy Python versions.
I confirmed that all of the test cases by `make test` are passed after the change.

Drop support for legacy Python versions: Issue #305

---

.travis.yml
test/tm-cases/fenced_code_blocks_leading_lang_space.html
test/tm-cases/fenced_code_blocks_safe_highlight.html
test/tm-cases/fenced_code_blocks_syntax_highlighting.html
test/tm-cases/fenced_code_blocks_syntax_indentation.html
test/tm-cases/issue3_bad_code_color_hack.html
test/tm-cases/syntax_color.html
test/tm-cases/syntax_color_opts.html

This PR fixes #281.
Looks like `Pygments` changed highlighting output since version 2.1.1
and the changes would not break any HTML appearance from browsers in these test cases.

Fix syntax highlighting test cases that depend on Pygments output: Issue #281

---

.travis.yml
setup.py
test/testall.py

All test cases succeeded in Python 3.7 without any warnings.
Therefore, I considered that `markdown2` supported Python 3.7

Add support for Python 3.7

---

tox.ini

`tox.ini` included Python versions that already dropped, and not include a supporting version (`Python 3.7`).

Update tox envlist to follow currently supported Python versions

---

MANIFEST.in
setup.cfg
setup.py

This PR adds a functionality to make packages for both `tar.gz` and `whl` (Wheel format).
For example:
```con
$ python setup.py build
...
$ ls dist
markdown2-2.3.6-py2.py3-none-any.whl  markdown2-2.3.6.tar.gz
```
You will need to change to specify both packages when uploading packages to PyPI:
```
twine upload dist/markdown2-2.3.6-py2.py3-none-any.whl dist/markdown2-2.3.6.tar.gz
```

Add Wheel package support: Issue #228

---

lib/markdown2.py
test/tm-cases/toc_5.html
test/tm-cases/toc_5.opts
test/tm-cases/toc_5.tags
test/tm-cases/toc_5.text
test/tm-cases/toc_5.toc_html

This PR fix issue #311 
`_toc_depth` initialization skipped if both `"toc"` and `"header-ids"` are specified to `extras`.
This will cause `AttributeError` in the later process.

Fix _toc_depth initialization: #311

---

lib/markdown2.py
test/tm-cases/CVE-2018-5773.html
test/tm-cases/CVE-2018-5773.text

More robust XSS check

---

lib/markdown2.py
test/tm-cases/footnotes_smarty-pants.html
test/tm-cases/footnotes_smarty-pants.opts
test/tm-cases/footnotes_smarty-pants.text

Refs #150 
I don't think this is a great solution to this problem, as clearly attributes in HTML should never be smart-quoted.
However, for this specific problem this patch is a fix.
I'd be happy to chat more about better ways of doing this and to work on a better fix.

Un-smart-quote footnote back refs

---

lib/markdown2.py
test/tm-cases/inline_links.html
test/tm-cases/inline_links.text
test/tm-cases/long_link.html

This was added as part of 000343d, but isn't necessary for that change,
and causes links like [`example`] to render as "&lt;code&gt...".
Fixes #259

Stop XML escaping the body of a link.

---

lib/markdown2.py
test/tm-cases/link_patterns_escape.html
test/tm-cases/link_patterns_escape.opts
test/tm-cases/link_patterns_escape.text

This allows the prevention of `[WikiWikiWeb](http://wiki.c2.com/?WikiWikiWeb)` being transformed to `<a href="http://wiki.c2.com/?&lt;a href=&quot;aw.cgi?page=WikiWikiWeb&quot;&gt;WikiWikiWeb&lt;/a&gt;">WikiWikiWeb</a>` when the pattern linker sees the second WikiCase word if the author surrounds it with triple quotes: so `[WikiWikiWeb](http://wiki.c2.com/?"""WikiWikiWeb""")` is now transformed to `<a href="http://wiki.c2.com/?WikiWikiWeb">WikiWikiWeb</a>`.
The function responsible, `_do_link_patterns()`, already checked for the cases that the pattern was inside square brackets, or was preceeded by `](` or suffixed by `")`, and skips expanding in these cases. This addition simply adds a check that the pattern is not surrounded by triple quotes; the triple quotes are stripped from the …

Don't auto link patterns surrounded by """.

---

lib/markdown2.py
test/tm-cases/html_classes.html
test/tm-cases/html_classes.opts
test/tm-cases/html_classes.tags

Adds support so you can customize the classes that decorate the enclosing `<p>` tags :)
Help for https://github.com/trentm/python-markdown2/issues/116

Add class configurability to the enclosing tag.

---

lib/markdown2.py
test/tm-cases/task_list.html
test/tm-cases/task_list.text

I'm a developer at @ccextractor and we will be using this project to send markdown to html emails in our CI system.
Github supports using either `[x]` or `[X]` in marking task list item. Unfortunately, markdown2 only converts `[x]` to checked list.
e.g.
I've changed the regex to accept [X] in the tasklist marked regex subgroup and consequently, we check using a conditional block.

Accept [X] as marked task

---

lib/markdown2.py
test/test_markdown2.py

Reset the _toc variable to None whenever a new conversion is performed.
Resolves #208

Reset _toc when convert is run

---

lib/markdown2.py
test/tm-cases/issue341_xss.html
test/tm-cases/issue341_xss.opts
test/tm-cases/issue341_xss.text

This will apply escaping on link text which can currently inject XSS
Fixes #341

Issue 341 - XSS in link text

---

lib/markdown2.py
test/php-markdown-extra-cases/Tables.html
test/php-markdown-extra-cases/Tables.text

Table alignment currently uses `align=left|center|right` which is a deprecated attribute with limited support in modern browsers.
At the moment I'm having to post-process the Markdown generated by markdown2.py in order to replace the aligns with text-align as we need good cross-browser support (notably, Firefox completely ignores the `align` attribute).
See:
* https://caniuse.com/#feat=mdn-html_elements_th_align
* https://caniuse.com/#feat=mdn-html_elements_td_align
This PR switches instead to the recommended and more widely-supported `style=text-align`: https://caniuse.com/#feat=mdn-css_properties_text-align
Additionally, in updating the tests I found that they contained a spelling error and that they have their lefts and rights switched (I double-checked the expected output for the …

Tables: use style=text-align for table alignment

---

lib/markdown2.py
test/tm-cases/metadata.metadata
test/tm-cases/metadata.text

Pull request fixing #120. All tests passes. Existing test on metadata is extended to cover new cases.
```yaml
key:
subkey: subvalue
```
is now parsed as `key: {subkey: subvalue}`
```yaml
key:
- one
- two
```
is now parsed as `key: ["one", "two"]`
```yaml
key:
subkey:
- >
Long text
in structure
```
is now parsed as `key: {subkey: ["Long text\n  in structure"]`
- Sub-elements can be indented by an arbitrary number of spaces or tabs, as soon as the indent is strictly identical for each element.
- Sub-elements must begin with a line return. syntax like `key: subkey: subvalue` is not supported.

Support for structured and nested values in metadata (#120)

---

lib/markdown2.py
test/tm-cases/link_with_blank.html

Adds `rel="noopener"` anytime a link contains `target="_blank"` for improved security.
https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/noopener

add noopener to external links

---

.travis.yml
setup.py

`3.9` isn't yet on Travis CI (give [this](https://travis-ci.community/t/python-3-9-0-build/10091?u=hugovk) a +1), `3.9-dev` is good for now.
Update Trove classifiers for 3.8 and 3.9.
Add `python_requires` to help pip.
And fix `Warning: 'classifiers' should be a list, got type 'filter'"` when running `python setup.py --classifiers` (or any `--help` or any option).

Add support for Python 3.8-3.9

---

lib/markdown2.py
test/tm-cases/metadata.metadata
test/tm-cases/metadata.text

Pull request fixing a bug I just discovered in the structured metadata feature I introduced in #368.
In metadata lists, strings elements were cut at the first space or `:` symbol encountered, instead of being kept completely as a string element.
I fixed the regex used to catch list elements and updated the test scenario to cover this case.

Fixed bug breaking strings elements in metadata lists

---

lib/markdown2.py
test/testall.py

Addresses two of the three warnings given in #343.  The third one was fixed as [part of a7da039c081a](https://github.com/trentm/python-markdown2/commit/a7da039c081aaeb7c6eb18bba0ab0d76661a2b39#diff-59161098c0c2d506b5700112a54eb00354b867f46fa501a9f68cd86d843f1b57L449).
Running `make test` gives 6 errors for me.  All of them look like minor changes in Pygments output.

Fix backslash deprecation warnings

---

test/testlib.py

There is a small typo in test/testlib.py.
Should read `because` rather than `becase`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: fix simple typo, becase -> because

---

lib/markdown2.py

Regex DOS vulnerability report via @b-c-ds
- Fixes two regex via proposed patches
- Band aid on fenced-code-block DOS by limiting the amount of spaces after language specification. Passes tests and common usage.
Full report with example fixes:
```
Doyensec Vulnerability Advisory 
=======================================================================
* Regular Expression Denial of Service (REDoS) in python-markdown2
* Affected Product: markdown2 >= 1.0.1.18
* Vendor: https://github.com/trentm
* Severity: Low
* Vulnerability Class: Denial of Service
* Status: Open
* Author(s): Ben Caller (Doyensec)
=======================================================================
=== SUMMARY ===
The python package markdown2 processes markdown using regular expressions which are vulnerable to Regular …
```

Regex DOS fixes

---

lib/markdown2.py
test/php-markdown-extra-cases/Tables.html
test/php-markdown-extra-cases/Tables.text

This tiny regex adjustment fixes https://github.com/trentm/python-markdown2/issues/325
I also added a test case that passes (fails before this patch).
`python test.py` has 15 failures for me, with or without this change.

Tables extra: allow whitespace at the end of the underline row

---

CHANGES.md
lib/markdown2.py
test/tm-cases/pyshell_and_fenced_code_blocks.html
test/tm-cases/pyshell_and_fenced_code_blocks.opts
test/tm-cases/pyshell_and_fenced_code_blocks.tags
test/tm-cases/pyshell_and_fenced_code_blocks.text

First of all, thanks for the fantastic project! We're very happily using it for [pdoc](https://pdoc.dev/). 😃 
This PR changes the behavior of the pyshell extra to rely on fenced-code-blocks for syntax highlighting if both extras are enabled. pygments has a [matching lexer](https://pygments.org/docs/lexers/#pygments.lexers.python.PythonConsoleLexer) for those ">>>" blocks, which makes the implementation quite straightforward.

pyshell: add syntax highlighting

---

.travis.yml

Currently, Python 3.10.0a5+ on Travis CI but 3.10.0alpha6 is released
https://www.python.org/downloads/release/python-3100a6/

Travis CI: Upgrade to Python 3.10-dev

---

lib/markdown2.py
test/tm-cases/metadata.metadata
test/tm-cases/metadata.text
test/tm-cases/metadata2.metadata
test/tm-cases/metadata2.text

When processing a multiline meta value like this:
```
another long: >
long value
with complex indentation
that goes multiline
```
The meta value for the "another long" key should look like:
```
long value
with complex indentation
that goes multiline
```
Instead this:
```
long value
with complex indentation
that goes multiline
```
Tested using:
```
cd test
PYTHONPATH=../lib python test.py -- -knownfailure
```

Fix meta indentation

---

lib/markdown2.py
test/tm-cases/quoted_fenced_code_blocks_whitespace_around_indented_lines.html
test/tm-cases/quoted_fenced_code_blocks_whitespace_around_indented_lines.opts
test/tm-cases/quoted_fenced_code_blocks_whitespace_around_indented_lines.tags
test/tm-cases/quoted_fenced_code_blocks_whitespace_around_indented_lines.text

Fix code surrounded by blank lines inside blockquote fenced code blocks being detected as code blocks.
This is a wordy and niche problem but in essence, this:
````
> ```python
> if True:
>     print()
> 
>     print()
> 
>     print()
> 
>     print()
> ```
````
Would be rendered like this:
```html
<blockquote>
<div class="codehilite"><pre><span></span><code><span class="k">if</span> <span class="kc">True</span><span class="p">:</span>
<span class="nb">print</span><span class="p">()</span>
<pre><code>&lt;span class="nb"&gt;print&lt;/span&gt;&lt;span class="p"&gt;()&lt;/span&gt;
&lt;span class="nb"&gt;print&lt;/span&gt;&lt;span class="p"&gt;()&lt;/span&gt;
</code></pre>
<span class="nb">print</span><span class="p">()</span>
</code></pre></div>
</blockquote>
```
This is because of the …

Fix code surrounded by blank lines inside blockquote fenced code blocks

---

lib/markdown2.py
test/tm-cases/fenced_code_blocks_issue327.html
test/tm-cases/fenced_code_blocks_issue327.opts
test/tm-cases/fenced_code_blocks_issue327.tags
test/tm-cases/fenced_code_blocks_issue327.text

As stated in issue #327, Markdown allows for inserting fenced code blocks within other fenced code blocks, provided that the outer code block has one more back-tick than the inner one.
EG :
``````
````
```cpp
int x = 10;
```
````
```````
The previous regex for fenced code blocks would look for lines starting with three back-ticks only. The new regex checks for lines starting with three or more back-ticks and then uses a back reference to find an identical closing set of back-ticks.
The disadvantage of this is that the opening back-ticks have to be captured for the back reference to work, which makes it the first group of the `re.Match` that gets passed to `_code_block_sub`

Fix code block parsing error (issue #327)

---

lib/markdown2.py
test/tm-cases/inline_code_pipe_within_table.html
test/tm-cases/inline_code_pipe_within_table.opts
test/tm-cases/inline_code_pipe_within_table.tags
test/tm-cases/inline_code_pipe_within_table.text

The issue (#399) was that this table:
```
| Sign | Operator name | Description |
|---|---|---|
| `&` | Bitwise and | Bitwise and between two integer values |
| `|` | Bitwise or | Bitwise or between two integer values |
```
Would be rendered incorrectly due to the "\`|`" being detected as part of the table, and not as the contents of the table.
The original regex (```^\||(?<!\\)\|```) for splitting a table by the cells within it would exclude pipe symbols preceded by a back-slash.
The updated regex (```^\||(?<![\`\\])\|```) will also exclude pipe symbols preceded by a backtick

Fix inline code pipe symbol within tables (issue #399)

---

lib/markdown2.py
test/tm-cases/fenced_code_blocks_issue355.html
test/tm-cases/fenced_code_blocks_issue355.opts
test/tm-cases/fenced_code_blocks_issue355.tags
test/tm-cases/fenced_code_blocks_issue355.text

The `_fenced_code_block_re` would look for fenced code blocks surrounded by `\n` characters.
However, if two code blocks were separated by only a single `\n` then that `\n` would be matched as part of the first code block. 
EG:
````
---
```          |
some code    |  The first code block, successfully matched
```          |
---
```         ---
some code    | What the regex tries to match against the second time
```         ---
````
The second code block is now without a preceding `\n`, due to the fact that overlaps are not allowed, and since code blocks are required to have a preceding and following `\n`, the second block does not get matched.
The proposed fix adds a look-behind assertion to check if the code block is preceded by a `\n` character, ignoring the overlap.
EG:
````
---
``` …

Fix unexpected md5-* in resulting HTML when several code blocks follow one by one (issue #355)

---

lib/markdown2.py
test/tm-cases/break_on_newline_excessive_br_tags_in_ul.html
test/tm-cases/break_on_newline_excessive_br_tags_in_ul.opts
test/tm-cases/break_on_newline_excessive_br_tags_in_ul.text

The `break-on-newline` extra uses a regexp to replace 0 or more spaces followed by a new line, with a `<br />` tag.
This is a problem for `<ul>`, `<ol>` and mixed lists, where list items are defined on new lines.
Something like
```
- Item 1
- Item 2
```
Could end up as:
```html
<ul>
<li>Item 1<br />
<ul><br />
<li>Item 2</li><br />
</ul></li>
</ul>
```
The proposed fix replaces 0 or more spaces followed by a new line, but only if they are not followed by a `ul`, `ol` or `li` opening/closing tag.

Fix excessive `<br>` tags in lists using `break-on-newline` extra (issue #394)

---

README.md
test/testall.py

This PR updates the test suite to no longer test against any Python version lower than 3.5.
Previously the test suite would detect installed python versions from a hard-coded list of supported versions, ranging from 2.6-2.7 and 3.3-3.7, which becomes out of date every year when Python has a new version release.
The proposed change generates Python version numbers from 3.5 up to (but not including) 3.20 which means that the upper end of the range shouldn't need to be changed for 8 or so years and the lower end of the range can easily be bumped up as older Python versions loose support.

Don't test library against unsupported Python versions.

---

lib/markdown2.py
test/tm-cases/metadata3.html
test/tm-cases/metadata3.metadata
test/tm-cases/metadata3.opts
test/tm-cases/metadata3.text

As discussed in #423 , the `_meta_data_pattern` regexp had some inconsistent definitions for what metadata `key:value` pairs were allowed to contain.
This PR defines keys as `[\S \t]*\w[\S \t]*\s*:` and values as `.*`
I found the keys much harder to define but the proposed definition:
- Requires at least one word character
- Can contain spaces, tabs, hyphens and other symbols
- Can have whitespace before the colon
- Feels somewhat clunky
Metadata values were much easier as I just used the most inclusive character class available.
This PR also removes the `_key_val_pat` and `_key_val_block_pat` class variables because I couldn't find anywhere in the codebase that they were being used.

Standardize key and value definitions for metadata extra (issue #423)

---

lib/markdown2.py
test/tm-cases/fenced_code_blocks_issue426.html
test/tm-cases/fenced_code_blocks_issue426.opts
test/tm-cases/fenced_code_blocks_issue426.tags
test/tm-cases/fenced_code_blocks_issue426.text

The problem was that fenced code blocks would not be detected if placed inside a list (ul/ol) due to
the leading indentation before the opening code fence.
This PR tweaks the `_fenced_code_block_re` to ignore leading space/tab indents before an opening fence.
`_code_block_sub` has also been altered to maintain the leading indentation when inserting code hashes as
to not break the list (ul/ol) that the fenced code block is in, so instead of this:
```html
<h2>URL PARAMETERS IN THE TEMPLATE</h2>
<ul>
<li>All views (except <code>md5-e492587862bc07a3e8a1766f3b6cdf9f</code>) from <code>md5-13862f106a0084500eb9518428d220d5</code> inherit from <code>md5-cb5cca48ea3a39d2e5f4f32ed57fe64e</code></li>
<li><code>md5-cb5cca48ea3a39d2e5f4f32ed57fe64e</code> defines the method …
```

Fix fenced code blocks breaking lists (issue #426)

---

lib/markdown2.py
test/tm-cases/fenced_code_blocks_issue426.html

In my previous PR (#427) I accidentally introduced a bug that would mess up the indentation of a fenced code block within a list.
I made the mistake of not checking the output of the `fenced_code_blocks_issue426.html` test case in a browser, where the bug is very obvious.
My previous fix would only add the leading indentation to the first line of the fenced code block. (facepalm).
This new fix is alot smarter. It takes a fenced code block like this:
````
```python
if True:
print('Stuff')
```
````
And it figures out what the smallest common indent is for each line. In this case, each line is indented by at least 4 spaces.
We then remove this leading indentation from the fenced code block like so:
````
```python
if True:
print('Stuff')
```
````
And run this code through the pygments …

Fix incorrect indentation of fenced code blocks within lists

---

CHANGES.md
lib/markdown2.py

Found in https://github.com/mitmproxy/pdoc/issues/376: The following docstring takes ages to process due to catastrophic backtracking:
```
Foo the foo.
> >>> class Foo(object):
> ...     pass
> >>> foo = Foo()
> >>> paths = foo.foo(dir_="src")
> >>> [str(p) for p in paths][:2]
> ['foo', 'bar']
```
This PR fixes the corresponding regular expression. :)

fix catastrophic backtracking in pyshell code blocks

---

lib/markdown2.py
test/tm-cases/admonitions.html
test/tm-cases/admonitions.opts
test/tm-cases/admonitions.text
test/tm-cases/admonitions_with_fenced_code_blocks.html
test/tm-cases/admonitions_with_fenced_code_blocks.opts
test/tm-cases/admonitions_with_fenced_code_blocks.tags
test/tm-cases/admonitions_with_fenced_code_blocks.text

This PR adds support for rendering RST admonitions as HTML `<aside>` blocks, as discussed in #401. This implementation was based on the spec laid out in the [docutils RST directives spec](https://docutils.sourceforge.io/docs/ref/rst/directives.html#admonitions).
Something like:
```rst
.. attention:: Title
Body
```
Will be rendered as:
```html
<aside class="admonition attention">
<strong>attention</strong>
<em>Title</em>
<p>Body</p>
</aside>
```
Firstly, the leading indentation of the admonition is captured. This is to make sure the processed HTML is put back into the document at the same indentation level to avoid breaking out of lists and such.
In the above example the leading indentation is 0 spaces until the start of the directive indicator but if you put an admonition inside of a list …

RST admonitions (#401)

---

lib/markdown2.py

Added an assertion to spit out a more descriptive error if `link-patterns` is not given a value.
Not sure how to add a test case for this though.

Improve error message if `link_patterns` forgotten (#428)

---

lib/markdown2.py

pygments 2.12 has changed the signature and behavior of `HtmlFormatter.wrap`. This PR adjusts markdown2 to handle both old and new versions.

fix compatibility with pygments 2.12

---

lib/markdown2.py
test/tm-cases/html_classes_is_none.html
test/tm-cases/html_classes_is_none.opts
test/tm-cases/html_classes_is_none.tags
test/tm-cases/html_classes_is_none.text

This PR tweaks the `html-classes` extra so that a TypeError will not be raised if HTML class mappings are not given.
````python
import markdown2
text="""
```
print("hello world")
```
"""
markdown2.markdown(text, extras=["html-classes"])
````
In the above example, no mapping was provided for the extra so the value defaults to `None`. When it gets around to checking if a certain tag is present in the html classes mapping, a type error occurs.
The proposed change simply checks if the html classes extra is an instance of `dict`, and if not it returns an empty string.

Fix `TypeError` if `html-classes` extra is None #391

---

.github/workflows/python.yaml

this adds tests for windows and macos to the build matrix as well.

extend github ci to include tests for windows and mac as well

---

CHANGES.md

Fix some formatting issues in `CHANGES.md` by wrapping HTML tags in backticks

Fix formatting in `CHANGES.md`

---

lib/markdown2.py
test/tm-cases/link_patterns_edge_cases.html
test/tm-cases/link_patterns_edge_cases.opts
test/tm-cases/link_patterns_edge_cases.text

Fixed link patterns extra applying to patterns that are already inside an auto link or a markdown link.
EG:
```python
import markdown2, re
patterns = [(re.compile(r'#([1-9][0-9]*)'), r'http://localhost/issue/\1')]
m = markdown2.Markdown(extras=['link-patterns'], link_patterns=patterns)
print(m.convert("""
<http://localhost/#42>
[Issue #42](http://localhost)
"""))
```
As demonstrated in #385, this would previously produce the output:
```html
<p><http://localhost/<a href="http://localhost/issue/42">#42</a>&gt;</p>
<p><a href="http://localhost/">Issue <a href="http://localhost/issue/42">#42</a></a></p>
```
But now should produce:
```html
<p><a href="http://localhost/#42">http://localhost/#42</a></p>
<p><a href="http://localhost/">Issue #42</a></p>
```
The fix works by searching for anything …

Fix link patterns extra applying within links (issue #385)

---

lib/markdown2.py
test/tm-cases/codespans_inside_link_text.html
test/tm-cases/codespans_inside_link_text.text

This PR fixes issue #344, where back-ticks would not work within links.
The solution works by ignoring encoded code spans in `_hash_html_spans`

Codespans inside link text issue344

---

lib/markdown2.py
test/tm-cases/emacs_file_vars.html
test/tm-cases/emacs_file_vars.opts
test/tm-cases/emacs_file_vars.text

This PR fixes a couple of issues.
**Issue 1:** `AttributeError` being raised when specifying some extras via emacs local variables
```python
> import markdown2
> text = "-*- markdown-extras: footnotes -*-\nRandom unimportant text"
> markdown2.markdown(text, use_file_vars=True)
AttributeError: 'Markdown' object has no attribute 'footnotes'
```
This error happened because the `self.footnotes` dictionary is created by the `self.reset()` function, which is called BEFORE the emacs local variables get parsed. This means that the `self.footnotes` dictionary doesn't get created because, when it is called, the footnotes extra has not been specified.
This PR puts the `self.footnotes` dict creation (and some other extras setup) into a separate `_setup_extras` function which gets called during …

Fix emacs local variable one-liners

---

lib/markdown2.py
test/tm-cases/issue276_fenced_code_blocks_in_lists.html
test/tm-cases/issue276_fenced_code_blocks_in_lists.opts
test/tm-cases/issue276_fenced_code_blocks_in_lists.tags
test/tm-cases/issue276_fenced_code_blocks_in_lists.text

This is a fix for issue #276. There's a failure in converting markdown lists that have fenced code blocks in them, because the indentation of the fenced code block is not accounted for unless syntax highlighting is enabled.
I also pulled out the code for substituting code blocks with a lexer into its own method so it is a little easier to read.

Fix code block indentation in lists

---

lib/markdown2.py
test/tm-cases/xss_issue_362.html
test/tm-cases/xss_issue_362.opts
test/tm-cases/xss_issue_362.text

As reported by @terjanq:
> The new regex `_incomplete_tags_re = re.compile("<(/?\w+?(?!\w).+?[\s/]+?)")` in [#351](https://github.com/trentm/python-markdown2/pull/351) introduced a more severe bypass on any HTML element by using a new line that does not match to .+.
> ```python
> In [2]: markdown2.markdown('<iframe\nonload=alert()//',safe_mode=True)
> Out[2]: '<p><iframe\nonload=alert()//</p>\n'
> ```
I was able to reproduce this issue.
The proposed change ignores whitespace between the tag name and the `.+` and from my tests this seems to do the trick.
```diff
- _incomplete_tags_re = re.compile("<(/?\w+?(?!\w).+?[\s/]+?)")
+ _incomplete_tags_re = re.compile("<(/?\w+?(?!\w)\s*.+?[\s/]+?)")
```
However, I will admit that I'm not a security guy so it's possible that this change has it's own …

Fix filter bypass leading to XSS (#362)

---

lib/markdown2.py
test/tm-cases/html_classes.html

The `html-classes` extra says it supports code tags but previously this was only applied to fenced code blocks when using the `fenced-code-blocks` extra. This PR modifies the `_code_span_sub` function to fix this omission and also updates the relevant test case.

Fix `html-classes` extra not applying to code spans

---

lib/markdown2.py
test/tm-cases/admonitions.html
test/tm-cases/break_on_newline_excessive_br_tags_in_ul.html
test/tm-cases/nested_list.html
test/tm-cases/nested_list.text

This PR fixes #275. The issue was that lists with multiple levels of nesting were being flattened. For example:
```markdown
* Item 2
- Subitem B following:
+ What
+ The
+ Code
```
Would become:
Which is obviously wrong. The bug came from the following line in the `_list_item_sub` function:
https://github.com/trentm/python-markdown2/blob/6032f8b5f95f579e0fc73c15ef7eaf6925e771bf/lib/markdown2.py#L1801
Once the above example reaches this line it is then outdented to:
```markdown
Item 2
- Subitem B following:
+ What
+ The
+ Code
```
Which now just resembles a normal list and will be processed as such.
This PR changes the `_list_item_sub` function to use the `_uniform_outdent` function, which produces the following output at the same point in the program, allowing nesting to be preserved. …

Fix multilevel lists

---

CHANGES.md
lib/markdown2.py
test/tm-cases/admonitions_with_fenced_code_blocks.html
test/tm-cases/fenced_code_blocks_issue355.html
test/tm-cases/fenced_code_blocks_issue426.html
test/tm-cases/fenced_code_blocks_issue462.html
test/tm-cases/fenced_code_blocks_issue462.opts
test/tm-cases/fenced_code_blocks_issue462.tags
test/tm-cases/fenced_code_blocks_issue462.text
test/tm-cases/fenced_code_blocks_leading_lang_space.html
test/tm-cases/fenced_code_blocks_safe_highlight.html
test/tm-cases/fenced_code_blocks_syntax_highlighting.html
test/tm-cases/fenced_code_blocks_syntax_indentation.html
test/tm-cases/issue276_fenced_code_blocks_in_lists.html
test/tm-cases/issue3_bad_code_color_hack.html
test/tm-cases/pyshell_and_fenced_code_blocks.html
test/tm-cases/pyshell_and_fenced_code_blocks.text
test/tm-cases/quoted_fenced_code_blocks_whitespace_around_indented_lines.html
test/tm-cases/syntax_color.html
test/tm-cases/syntax_color_opts.html

This PR is a fix for https://github.com/mitmproxy/pdoc/issues/421. Consider the following Markdown:
`````markdown
```python
x = 1
```
<div>
test
</div>
`````
markdown2 would previously first convert the fenced code block to `<div class="codehilite">...</div>`, and then, in `_hash_html_blocks`, match from the first pygments `<div class="codehilite">` to the final `</div>` at the end of the file[^1]. Everything in between (such as `# Section 2`) would be skipped.
I also considered to directly hash the pygments output instead (https://github.com/mhils/python-markdown2/commit/9622c0508ec7b1dc70dfb1b9918b0c1da34bba21), but that changes `<p>` paragraph wrapping and would be more of a breaking change. So I think this approach is preferrable.
[^1]: `_strict_tag_block_re` does this before …

Fix pygments block matching

---

CHANGES.md
lib/markdown2.py
test/tm-cases/ordered_list_lazy_numbering.html
test/tm-cases/ordered_list_lazy_numbering.text

This PR closes #469 by adding support for ordered lists that don't start at 1, making use of the "start" attribute for `<ol>` tags.
Example input:
```markdown
2. Item 1
3. Item 2
```
Previous output:
```html
<ol>
<li>Item 1</li>
<li>Item 2</li>
</ol>
```
New output:
```html
<ol start="2">
<li>Item 1</li>
<li>Item 2</li>
</ol>
```

Add support for ordered lists that don't start at 1. (issue #469)

---

CHANGES.md
lib/markdown2.py
test/tm-cases/ordered_list_lazy_numbering_issue471.html
test/tm-cases/ordered_list_lazy_numbering_issue471.opts
test/tm-cases/ordered_list_lazy_numbering_issue471.text

This PR fixes #471.
The issue was with an assertion that ordered lists must start with `<ol>` which, since c3d4e41, may no longer be the case. This PR updates that assertion to match `r'^<(?:ul|ol).*?>'` which should allow for list tags with attributes.

Fix `AssertionError` with lazy numbered lists (issue #471)

---

CHANGES.md
lib/markdown2.py

This PR removes the `_uniform_outdent_limit` function and integrates it's functionality into the `_uniform_outdent` function.
Previously, the `_uniform_outdent_limit` function was just a clone of `_uniform_outdent` that allowed one to set a maximum level of outdentation to occur.
The new, re-written `_uniform_outdent` function allows for this functionality as well as setting a minimum outdentation level, to force all lines to be outdented by `min_outdent` or greater.

Re-write `_uniform_outdent` function and remove `_uniform_outdent_limit` function

---

lib/markdown2.py
test/tm-cases/nested_incomplete_tags_xss.html
test/tm-cases/nested_incomplete_tags_xss.opts
test/tm-cases/nested_incomplete_tags_xss.text

Hi, this is just a test demonstrating nested incomplete tags resulting in XSS. As there. have been multiple bypasses since I reported https://github.com/trentm/python-markdown2/issues/285, I still think introducing Bleach might be worthwhile. Perhaps in a major version as it might involve breaking changes for rendering. Bleach is a bit more aggressive than current implementation for escaping and replacing in markdown2.
```
>>> bleach.clean('<blah/<img src="" onerror=alert(/XSS/)')
''
```

Add test for nested incomplete tag sanitization

---

.github/workflows/python.yaml
CHANGES.md
README.md
setup.py

Previously, if a user wanted to make sure optional features of markdown2 (such as code syntax highlighting) were enabled and working, they would have to know to install the optional dependencies (EG: Pygments) for these features to work.
This PR adds the `extras_require` key to `setup.py` to define these optional dependencies, enabling users to do:
```
pip install markdown2[code_syntax_highlighting]
```
To install markdown2 as well as Pygments>=2.7.3 (the earliest version I found that still passes all tests) for code highlighting.
I also added an "all" extra that automatically combines all the other extras to allow a short, convenient and easily memorable way to make sure all optional dependencies are installed.
```
pip install markdown2[all]
```

Add optional dependencies to `setup.py`

---

CHANGES.md
lib/markdown2.py
test/tm-cases/mix-ordered-and-unordered-lists.html
test/tm-cases/mix-ordered-and-unordered-lists.text

This PR fixes #478.
The issue was, as described in #478, mixing ordered and unordered lists like so:
```markdown
1. Lorem Ipsum
2. Lorem Ipsum
- Lorem Ipsum
- Lorem Ipsum
```
Which would produce:
```html
<ol>
<li>Lorem Ipsum</li>
<li>Lorem Ipsum</li>
<li>Lorem Ipsum</li>
<li>Lorem Ipsum</li>
</ol>
```
Which completely ignores the fact that the list type changes halfway down. This PR updates the list regex in `_do_lists` to check for a change of list type to produce the following output:
```html
<ol>
<li>Lorem Ipsum</li>
<li>Lorem Ipsum</li>
</ol>
<ul>
<li>Lorem Ipsum</li>
<li>Lorem Ipsum</li>
</ul>
```

Fix mixing ordered and un-ordered lists combining into single list type.

---

lib/markdown2.py

This PR is for an ever so slight refactoring of the regular expression used for the markdown metadata extra.
The `_meta_data_pattern` regex is gnarly and awful to look at. This commit makes this a little bit better by using string formatting to substitute in repeated values, such as the definitions for opening fences and metadata keys.
This should reduce repetition and make it easier to change these definitions in the future.

Slight refactor of the `_meta_data_pattern` regex

---

lib/markdown2.py
test/tm-cases/hash_nested_html_blocks.html
test/tm-cases/hash_nested_html_blocks.opts
test/tm-cases/hash_nested_html_blocks.tags
test/tm-cases/hash_nested_html_blocks.text
test/tm-cases/sublist-para.html

This PR fixes #481 by fixing `_hash_html_blocks` matching the wrong HTML closing tag when hashing HTML blocks.
An example like this:
```html
<div class="enclosing">
<div class="codehilite">
<pre><span></span><code><span class="n">x</span> <span class="o">=</span> <span class="mi">1</span>
</code></pre>
</div>
</div>
```
Would end up with the final closing `</div>` tag wrapped in `<p>` tags as the `_strict_block_tag_re` failed to match against the whole `<div>` block correctly.
This fix solves this issue by iterating over the given text and manually tallying up the number of opening and closing `<div>` tags and then hashing the relevant block.

Fix hashing nested HTML blocks

---

CHANGES.md
lib/markdown2.py
test/tm-cases/backslash_escape_html_tags.html
test/tm-cases/backslash_escape_html_tags.text

This PR fixes #386, allowing the use of backslashes to escape HTML tags, auto-links and HTML comments.
It works by checking for pairs of backslashes preceding any markup. If there are 0 or more pairs of backslashes (eg: `\\\\`) then they escape themselves. If there is an odd number of backslashes then the markup has been escaped.

Fix backslash being unable to escape raw HTML tags

---

test/test.py
test/tm-cases/fenced_code_blocks_safe_highlight.html
test/tm-cases/fenced_code_blocks_safe_highlight.tags
test/tm-cases/fenced_code_blocks_safe_highlight_old.html
test/tm-cases/fenced_code_blocks_safe_highlight_old.opts
test/tm-cases/fenced_code_blocks_safe_highlight_old.tags
test/tm-cases/fenced_code_blocks_safe_highlight_old.text
test/tm-cases/fenced_code_blocks_syntax_highlighting.html
test/tm-cases/fenced_code_blocks_syntax_highlighting.tags
test/tm-cases/fenced_code_blocks_syntax_highlighting_old.html
test/tm-cases/fenced_code_blocks_syntax_highlighting_old.opts
test/tm-cases/fenced_code_blocks_syntax_highlighting_old.tags
test/tm-cases/fenced_code_blocks_syntax_highlighting_old.text

As mentioned in #496, pygments 2.14 broke some of the tests around syntax highlighting.
This PR updates the test cases to include tests for Pygments<2.14 and Pygments>=2.14, which will be ran depending on what version of pygments you have installed

Fix tests for Pygments 2.14

---

CHANGES.md
lib/markdown2.py
test/tm-cases/consecutive_image_links_issue498.html
test/tm-cases/consecutive_image_links_issue498.text

The issue was with the image processing in `_do_links`.
`anchor_allowed_pos` was not being set when images were processed. This was fine before #487 because when a markdown link was processed, the resulting text was usually longer, allowing `anchor_allowed_pos` to fall behind where the next link started.
After #487, URLs started to be hashed, which meant that the processed link could be shorter than the original text, meaning `anchor_allowed_pos` would overlap the start of the next link.
This PR fixes that by making sure `anchor_allowed_pos` is set correctly when processing links

Fix images not being procesed correctly (#498)

---

lib/markdown2.py
test/tm-cases/html_classes.html
test/tm-cases/html_classes.opts

PR to add `<thead>` tag to `html-classes` extra to support html classes for the header row of the table.

Add <thead> tag to html-classes extra

---

CHANGES.md
lib/markdown2.py

`optparse` was deprecated since Python 3.2. This PR removes it in favour of the more modern `argparse` library

Replace deprecated `optparse` with `argparse`

---

CHANGES.md
lib/markdown2.py
test/tm-cases/link_patterns_hash_matching_issue287.html
test/tm-cases/link_patterns_hash_matching_issue287.opts
test/tm-cases/link_patterns_hash_matching_issue287.text

This PR fixes #287 by preventing any link pattern regular expressions from matching against internal hashes.
It does this by checking the overlap between any link pattern match and the positions of the hashes in the text.
If a link pattern matches against text inside the start-end positions of an internal hash, it is ignored.

Fix link patterns extra matching against internal hashes

---

CHANGES.md
lib/markdown2.py
test/tm-cases/hash_html_blocks_issue_508.html
test/tm-cases/hash_html_blocks_issue_508.text

This PR fixes #508 by patching the close tag detection in the strict block tag hashing function.
The issue was with lines such as:
```html
<div><div></div>
</div>
```
Where the first opening `<div>` tag would be deemed as "closed" because there was a closing `</div>` tag present on the same line.
The fix is to count the number of opening and closing tags on a single line. If they are inequal, the tag is deemed "open".

Fix HTML elements not unhashing correctly (issue 508)

---

CHANGES.md
test/testlib.py

This PR closes #510 by removing the dprecated `imp` module from the test suite, in favour of the `importlib` module

Remove deprecated imp module (issue #510)

---

CHANGES.md
lib/markdown2.py

This PR allows the user to pass in link patterns via the `extras` argument.
Previously, the user would have to remember to set two arguments correctly:
```python
markdown(text, extras=['link-patterns'], link_patterns=[...])
markdown(text, link_patterns=[...])  # doesn't raise but doesn't activate extra
markdown(text, extras=['link-patterns'])  # raises error
markdown(text, extras={'link-patterns': [...]})  # raises error
```
This PR enables that last use case

Allow link patterns to be passed via extras dict

---

CHANGES.md
lib/markdown2.py
test/tm-cases/basic_safe_mode.html
test/tm-cases/relative_links_safe_mode.html
test/tm-cases/relative_links_safe_mode.opts
test/tm-cases/relative_links_safe_mode.text

This PR fixes #254 by cherry-picking commit  pknowles@76c663d and adding a test case for this bug.
I removed the full MIT license text from the original commit, keeping the copyright attributions and a link to the license instead.
For such a small snippet of code, I think this approach is sufficient? In-lining is messy and I'm not sure where else the license would be stored.
Happy to hear feedback on this

Fix relative links not working in safe mode (issue #254)

---

lib/markdown2.py
test/tm-cases/markdown_in_html_in_lists.html
test/tm-cases/markdown_in_html_in_lists.opts
test/tm-cases/markdown_in_html_in_lists.text
test/tm-cases/nested_list.html
test/tm-cases/nested_list.text
test/tm-cases/seperated_list_items.html
test/tm-cases/seperated_list_items.text

```markdown
- Item 1
ABCDEF
- Item 2
- Item 3
- Item 4
```
While processing `Item 2`, `Item 4` would erroneously be flattened to the same level as `Item 3`.
In `_list_item_sub` if the last processed list item (in this case `Item 1`) ended with `\n\n`, the current list item would be passed to `self._outdent`, flattening the child list items.
This bug was fixed by instead passing the current list item to `self._uniform_outdent` and outdenting it by 1-4 spaces. 
The `_list_item_sub` function assumes that most list items, if they don't contain `\n\n`, should be run through the span gamut.
This assumption causes the following markdown to be incorrectly converted:
```markdown
- Item 1
<div markdown="1">
Some text
</div>
```
List items are allowed to contain `div` blocks, which can contain other …

Fix two list item related bugs

---

test/testall.py

This PR fixes #458.
It works by capturing and reading each line of each test runner's `stderr` in real time. If the line contains a warning it is saved to be re-printed later. Once all of the tests have finished, the warnings are printed to `stdout` along with the version of Python that raised the warning.

Clearer warning when not all tests are ran

---

CHANGES.md
lib/markdown2.py
test/tm-cases/link_safe_urls.html
test/tm-cases/link_safe_urls.text

This PR fixes #517 by expanding the scope of the `_safe_href` regex to include more types of relative links.
Previously, #513 was merged which allowed the following kinds of relative links:
```
[issue1](./issue1)
[issue1](/issue1)
```
But did not allow this: `[link](issue1)`
The new regex should allow URLs to omit the protocol section of the URL or use relative paths instead of a protocol (eg: `./`, `../`, `/`) followed by a hostname, optional port number and then the rest of the URL.
I've also expanded the number of accepted protocols to include `mailto:` and `tel:`.
Also, the `_safe_protocols` attribute has been re-introduced to allow users to extend the number of allowed protocols when operating in safe mode (see [this comment](https://github.com/trentm/python-markdown2/issues/517#issue …

Allow more relative links in safe mode (issue #517)

---

CHANGES.md
lib/markdown2.py
test/tm-cases/middle_word_em.html
test/tm-cases/middle_word_em.opts
test/tm-cases/middle_word_em.text

This PR closes #38 by adding an extra to disable emphasis syntax when in the middle of a word.
The current behaviour of the library is to always convert `this_text_here` to `this<em>text</em>here`. However, this is not always desirable, as highlighted in #38.
The new `middle-word-em` extra will allow users to allow (default) or disallow this behaviour by passing `extras={'middle-word-em': True/False}`. When disabled, any emphasis will be required to have a word boundary (`r'\b'`) surrounding it.
For backwards compatibility, I've kept the default behaviour as allowing middle word emphasis. Users must explicitly disable it. Passing `extras=['middle-word-em']` will not work.

Add `middle-word-em` extra

---

CHANGES.md
lib/markdown2.py
test/tm-cases/hash_html_blocks.html
test/tm-cases/hash_html_blocks.text

This PR fixes #185 by always restoring hashed html blocks at the end of conversion.
The original markdown snippet was as follows:
```html
<div
>
<h3>Archons of the Colophon</h3>
<p>by Paco Xander Nathan
</p>
</div>
```
The `<p>` tag would be hashed by the strict block sub but the enclosing `<div\n>` would only be caught by the liberal block sub, leading to nested hashes.
Nested hashes don't get fully unravelled in `_form_paragraphs`, only 1 layer does, so hashes would remain in the text until the end of the conversion process.
Since `_unescape_special_chars` doesn't process HTML blocks (only special chars and code blocks), the hash would remain in the final output.
What I've done is make sure that `_unescape_special_chars` also processes HTML blocks when performing its un-hashing.

Always restore hashed HTML blocks (issue #185)

---

CHANGES.md
lib/markdown2.py
test/tm-cases/script-and-style-blocks.html
test/tm-cases/script-and-style-blocks.text

This PR fixes #523 by adding `|style` to the `_block_tags_a` regex. This allows the contents of `<style>` tags to be hashed at the start of conversion, before any character escaping takes place, preserving the contents for the final output.

Fix angles being escaped in style blocks (issue #523)

---

lib/markdown2.py
setup.py

This PR fixed [#493](https://github.com/trentm/python-markdown2/issues/493) 
It uses a loop and some checking to avoid using regex that contains ReDoS vulnerabilities

repair a ReDoS vulnerability in markdown2.py

---

CHANGES.md
lib/markdown2.py

This PR fixes [this comment](https://github.com/trentm/python-markdown2/pull/531#issuecomment-1766880215) by applying the same fixes from #531 to the code friendly strong re

Fix #493 persisting when `code-friendly` extra enabled

---

CHANGES.md
lib/markdown2.py
test/tm-cases/header_ids_4.html
test/tm-cases/toc_4.html
test/tm-cases/toc_4.toc_html

This PR fixes #534 by updating the `_slugify` function to use utf-8 encoding instead of ascii.
I've also updated a few test cases that expected non-ascii characters to be ignored

Update `_slugify` to use utf-8 encoding (issue #534)

---

CHANGES.md
lib/markdown2.py
test/tm-cases/footnotes_order_of_appearance.html
test/tm-cases/footnotes_order_of_appearance.opts
test/tm-cases/footnotes_order_of_appearance.text

This PR closes #533 by making sure footnotes maintain their order of appearance in the final HTML.
Previously, the order of the final footnotes list was based on the insertion order of `footnote_ids`. This array was populated as the parser processed the text and encountered footnotes. The problem is that markdown isn't processed entirely in order, leading to a disorganised footnotes list being generated.
This PR changes this by instead using the insertion order of `footnotes`, which is populated at the beginning of the conversion process by `_strip_footnote_definitions`.
The result is that the generated list of footnotes will appear in the same order as the footnote definitions.

Maintain order of appearance in footnotes

---

CHANGES.md
lib/markdown2.py
test/tm-cases/mixed_header_ids.html
test/tm-cases/mixed_header_ids.opts
test/tm-cases/mixed_header_ids.text
test/tm-cases/mixed_header_ids.toc_html

This PR closes #537 by adding the capability to parse `<h[1-6]>` tags and include their IDs in the table of contents.
It works by matching HTML header tags, checking for an `id=` attribute and then adding an entry to the TOC. If the tag does not have an ID, a new one is generated and inserted into the HTML.
Since HTML content is hashed before markdown headers are processed, this step intercepts headers in `_hash_html_block_sub` before they get hashed. This means that TOC entries are inserted out of order. To fix this, I added a function that sorts the TOC by order of appearance.
It works by taking the TOC header entry, searching the text for that header and returning the index at which it is found.
This new headers behaviour is disabled by default, and can be enabled using the new …

Include HTML headers in TOC

---

lib/markdown2.py
test/tm-cases/toc_duplicate_entries.html
test/tm-cases/toc_duplicate_entries.opts
test/tm-cases/toc_duplicate_entries.text
test/tm-cases/toc_duplicate_entries.toc_html

This PR contains a fix for a bug that was introduced in #538, where duplicate entries could be added to the TOC when mixed headers were in use.
The issue was in the `_header_id_exists`, where I was attempting to check that a header ID already existed. The function only checked for the header ID in `_count_from_header_id`, which contained the base ID but not the suffixed ones (eg: `abc-1`).
This PR has fixed this by also checking in the TOC itself for any header IDs that match.

Fix duplicate entries in TOC when using mixed headers

---

CHANGES.md
lib/markdown2.py
test/tm-cases/trailing_table_whitespace.html
test/tm-cases/trailing_table_whitespace.opts
test/tm-cases/trailing_table_whitespace.text

This PR fixes #549 by modifying the tables regex to allow trailing whitespace on the end of each row.

Fix tables with trailing whitespace not being recognized (#549)

---

test/test_markdown2.py

This PR tweaks the test harness so that it always normalises EOLs in test files, regardless of the host OS.
This caught me when I was checking out between commits and branches. Git restored some files as `\r\n` instead of `\n` and the test suite started failing because the generated markdown didn't match, despite my local copy being in the same state as remote master.

Always normalise EOLs in test harness

---

CHANGES.md
lib/markdown2.py
test/tm-cases/markdown_in_html_on_same_line.html
test/tm-cases/markdown_in_html_on_same_line.opts
test/tm-cases/markdown_in_html_on_same_line.text

This PR closes #546 by enabling the `markdown-in-html` extra to parse snippets where the markdown is on the same line as the HTML block. For example:
```html
<p markdown="1">**text**</p>
```
The fix works by detecting whether the number of matched lines is less than 3 (meaning opening tag, closing tag and content aren't all on separate lines). The first line is then split after the opening tag, and the last line is split before the closing tag.
```python
['<p markdown="1">**text**</p>']          # initial list of lines
['<p markdown="1">', '**text**</p>']      # after first line is split
['<p markdown="1">', '**text**', '</p>']  # final state
```
This allows the extra to continue as normal

Update `markdown-in-html` extra to handle markdown on same line as HTML (#546)

---

test/testall.py

Regarding the removal of `os.WEXITSTATUS`: It doesn't exist on Windows, and generally I didn't find anything online saying that it has to be used for anything but the return value of `os.system`.

Make tests work on win32

---

CHANGES.md
lib/markdown2.py
test/tm-cases/link_after_square_brackets.html
test/tm-cases/link_after_square_brackets.text

This PR fixes #552.
The issue was with links following square brackets, eg: `[text][link](google.com)`. The link parser would hit `[text][link]` and correctly identify that this isn't a valid link. It would then set the current position counter to the end of the entire "match", which included the section containing the valid link.
I've changed it to set the current position to directly after the first square brackets, so that it picks up on the link right after

Fix incorrect parsing of links after square brackets (#552)

---

CHANGES.md
lib/markdown2.py
test/tm-cases/tables.html
test/tm-cases/tables.text

This PR closes #557 by modifying  the tables implementation to allow tables to be cuddled to the preceding paragraph.
As mentioned in the issue, the original tables implementation appears to be based on GFM and intentionally disabled this behaviour. GFM currently allows cuddled tables, so this change just brings the extra back up to speed with that.

Allow cuddled tables (#557)

---

CHANGES.md
lib/markdown2.py
test/tm-cases/markdown_in_html_on_same_line.html
test/tm-cases/markdown_in_html_on_same_line.text

This PR fixes #558, which is a continuation from #546.
The issue is regarding `markdown-in-html` tags that are not on their own line. This issue was partially fixed in #547, but the solution was gated behind a check for `if len(lines) < 3`.
This check was based on the assumption that the snippets would look like this:
```html
<div markdown="1">Some **text**
</div>
```
This assumption completely breaks down for longer snippets, leading to HTML tags not being properly split from the surrounding markdown.
This PR fixes this by always attempting to split the HTML tags into separate lines

Fix `markdown-in-html` not always splitting HTML tags into separate lines (#558)

---

CHANGES.md
lib/markdown2.py
test/tm-cases/basic_safe_mode_escape.html
test/tm-cases/basic_safe_mode_escape.text

This PR fixes #563 by amending the `_incomplete_tags_re` to also search for HTML comments. This change means that unclosed/incomplete HTML comments will be properly escaped and won't result in the rest of the document being commented out.

Fix incomplete comments in safe mode not being escaped (#563)

---

CHANGES.md
lib/markdown2.py
test/tm-cases/markdown_in_html_in_lists.html
test/tm-cases/markdown_in_html_in_lists.text

This PR closes #565 by fixing a bug where an HTML snippet inside of a list could cause the library to crash when `markdown-in-html` is enabled.
The issue is due to how `_markdown_in_html` handles indentation.
```
- one two
<p markdown="1">
def
</p>
- three four
```
In the above snippet, the HTML is placed inside a list because `_hash_html_blocks` doesn't work in lists (see #514), which means the snippet gets passed to `_do_markdown_in_html`.
The text is then dedented using `_uniform_outdent` which removes the smallest common leading indentation. Since the opening tag is indented further than the rest, it is left with a slight indentation.
The block is then passed to `_hash_html_block_sub` where multiple regular expressions expect the tag to be right at the start of the line. This causes a …

Fix crash in `markdown-in-html` extra (#565)

---

CHANGES.md
lib/markdown2.py
test/tm-cases/toc_prepend.html
test/tm-cases/toc_prepend.opts
test/tm-cases/toc_prepend.tags
test/tm-cases/toc_prepend.text
test/tm-cases/toc_prepend.toc_html

This PR closes #397 by adding a flag that enables the TOC to be prepended to the output text.
```python
markdown2.markdown(text, extras={'toc': {'prepend': True}})
```
This option is off by default to maintain backward compatibility

Add `prepend` arg to toc extra (#397)

---

CHANGES.md
test/test_markdown2.py
test/testall.py
test/tm-cases/link_patterns.opts
test/tm-cases/link_patterns_double_hit.opts
test/tm-cases/link_patterns_edge_cases.opts
test/tm-cases/link_patterns_escape.opts
test/tm-cases/link_patterns_hash_matching_issue287.opts
test/tm-cases/link_patterns_markdown_syntax.opts

This PR fixes a number of syntax warnings being raised in the test suite regarding invalid escape sequences. I also modified the test runner to make these warnings much more visible in the future

Fix syntax warnings in test suite

---

CHANGES.md
lib/markdown2.py
test/tm-cases/block_like_spans.html
test/tm-cases/block_like_spans.text

This PR closes #571.
Sometimes, inline tags (such as `<a>`) are written over multiple lines for readability, which makes them look alot like block elements. When spread out over multiple lines, the opening and closing tags would be detected as paragraphs and wrapped in `<p>` tags, which is invalid.
This PR avoids this by hashing these block-like spans to protect them from `_form_paragraphs`. The contents of these are run though `_run_span_gamut` in case there's any markdown in there. Since inline tags shouldn't contain block tags, we don't need to worry about processing any blocks.
The list of span tags was taken [from here](https://www.w3schools.com/htmL/html_blocks.asp).

Process inline tags as HTML blocks when they span multiple lines (#571)

---

lib/markdown2.py
setup.py
test/test.py
test/tm-cases/latex.html
test/tm-cases/latex.opts
test/tm-cases/latex.tags
test/tm-cases/latex.text

This extra converts inline and block latex in markdown to MathML
Closes #366 and #134
[GitHub Gist with example](https://gist.github.com/navanchauhan/041c91d0181be95add33c26d61f6433f)

Add new LaTeX Extra

---

lib/markdown2.py
test/tm-cases/not_quite_a_list_cuddled_lists.html
test/tm-cases/not_quite_a_list_cuddled_lists.opts
test/tm-cases/not_quite_a_list_cuddled_lists.text

Fixes: https://github.com/trentm/python-markdown2/issues/577
When `"cuddled-lists"` extra is passed, if you encounter ASCII art or any invalid list such as: `- - - Test`, an `AssertionError` is thrown due to the inability to parse it as a list and therefore the result text not containing the expected list structure.
- Instead of throwing an assertion error, we simply treat the unparsed text as the paragraph text.
- Added a regression test to reproduce the assertion error

Graceful handling of broken lists when cuddled-lists extra is enabled

---

CHANGES.md
lib/markdown2.py
setup.py
test/testall.py

This PR closes #562 by adding type hints to the library, dropping Python 3.6 and 3.7 support in the process.
3.6 and 3.7 were recently dropped from the test suite after Github removed them from CICD. It doesn't make sense to claim support for versions we don't test so I dropped them completely.
I've added type hints to pretty much every function. The `Markdown` object should be covered and most of the extras should either be explicitly covered or inferred through the type hints attached to the `Extra` base class.
All of the public API and a decent amount of the internal functions should be covered. The main gaping hole at the moment is the `extras` dict/param for the `Markdown` object. It's currently annotated as `Dict[str, any]` (after it's been massaged in the constructor), which is …

Add type hints (#562)

---

CHANGES.md
lib/markdown2.py
test/tm-cases/fenced_code_blocks_simple.html
test/tm-cases/fenced_code_blocks_simple.text

This PR fixes #580.
The `FencedCodeBlocks` extra wasn't adding the correct indentation to the closing `</code></pre>` tags, which would break the HTML when inside lists.

Fix fenced code blocks breaking lists (#580)

---

lib/markdown2.py
test/tm-cases/issue341_xss.html
test/tm-cases/issue583_xss.html
test/tm-cases/issue583_xss.opts
test/tm-cases/issue583_xss.text

This PR closes #583 by tweaking the incomplete tags regex. It now accounts for the token not having a trailing space.
That issue highlighted some larger issues  that this PR doesn't address, such as some assumptions made in the HTML span hasher. That will have to be looked into separately but this PR should patch the highlighted case

Fix #583 by tweaking incomplete tag regex

---

CHANGES.md
lib/markdown2.py
test/tm-cases/code_friendly_bold.html
test/tm-cases/code_friendly_bold.opts
test/tm-cases/code_friendly_bold.text

This PR fixes #589, which saw a regression for the following snippet:
```
**bold_but_not_emphasized**
```
This regression was introduced in fcaadfe when the `code-friendly` extra was converted to the new `Extra` format.
Prior to this change we had two different versions of the strong/em regexes and we'd run one or the other. That's not possible in the new format so the `CodeFriendly` extra runs before italics and bold and hashes text to protect it from the regex.
Currently it only hashes text if it's using the `_underscore bold syntax_`, but for `*star syntax*` it doesn't check if the text contains any underscores, which is how this can slip through.
I've modified the extra to check for underscores within the bold text. It will now hash that text, protecting it from the strong/em regex, …

Fix underscores within bold text getting emphasized (#589)

---

lib/markdown2.py
test/tm-cases/alerts.html
test/tm-cases/alerts.opts
test/tm-cases/alerts.text

This PR adds an `Alert` extra, which can be used to render [GitHub Markdown Alerts](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts).

Add `Alerts` extra

---

CHANGES.md
lib/markdown2.py
test/tm-cases/issue603_xss.html
test/tm-cases/issue603_xss.opts
test/tm-cases/issue603_xss.text

This PR fixes #603.
The issue was with image URLs and code blocks. Putting a code block in the image URL (``![](`code here`)``) caused the URL to be hashed and protected from further modification. Code blocks are expected to contain URL unsafe characters like quotes so this is normal.
The problem was that in `_protect_url`, we attempt to escape any URL unsafe characters, but since the URL has been hashed it is ineffective.
This PR fixes this by completely unhashing the image URL before passing it to `_protect_url`, which allows special characters to be escaped

Fix XSS injection in image URLs (#603)

---

CHANGES.md
lib/markdown2.py
test/tm-cases/issue601_xss.html
test/tm-cases/issue601_xss.opts
test/tm-cases/issue601_xss.text

This PR fixes #601 by making the HTML tokenisation regex more lenient.
Currently, the regex matches HTML tags and their attributes, using `[\w-]` for the attribute name. However, in the [HTML spec](https://html.spec.whatwg.org/multipage/syntax.html#attributes-2) it says:
> Attribute names must consist of one or more characters other than [controls](https://infra.spec.whatwg.org/#control), U+0020 SPACE, U+0022 ("), U+0027 ('), U+003E (>), U+002F (/), U+003D (=), and [noncharacters](https://infra.spec.whatwg.org/#noncharacter)
The current character class being used does not include all these possibilities so I've updated it to instead exclude these banned characters: `[^<>"'=/]`.
I also tweaked how the attribute values are matched. The current regex only allows for quoted values, which lets …

Fix XSS issue in safe mode (#601)

---

lib/markdown2.py

See #599 for the issue.
This PR generates the `SECRET_SALT` with urandom instead of bytes(randint(0, 1000000)), making the SALT realistically unguessable, and also improving the performance a bit.
I'm using `urandom` instead of `secrets` because it'll keep the library compatible with its current supported Python versions (3.5+).

Use urandom for SECRET_SALT

---

.github/workflows/python.yaml
CHANGES.md
lib/markdown2.py
perf/gen_perf_cases.py
perf/perf.py
perf/strip_cookbook_data.py
perf/util.py
sandbox/wiki.py
setup.cfg
setup.py
test/markdown.py
test/test.py
test/test_markdown2.py
test/testall.py
test/testlib.py
tools/cutarelease.py
tox.ini

* Add support for Python 3.13: https://discuss.python.org/t/python-3-13-0-final-has-been-released/66972/1
* Drop support for EOL Python 3.8: https://discuss.python.org/t/python-3-8-is-now-officially-eol/66983/1
* Upgrade syntax with pyupgrade `--py39-plus`
* Remove universal wheels, only needed when supporting both Python 2 and 3
* Remove redundant version checks
* Fix tox: 'failed with make is not allowed, use allowlist_externals to allow it'

Add support for Python 3.13, drop EOL 3.8

---

CHANGES.md
lib/markdown2.py
test/tm-cases/middle_word_em_with_extra_ems.html
test/tm-cases/middle_word_em_with_extra_ems.opts
test/tm-cases/middle_word_em_with_extra_ems.text

This PR fixes #606 by altering the regex used in `middle-word-em` so that it doesn't match against intentional emphasis markers.
Previously, a snippet such as `**one_two_three**` would have been matched aside from the last character. This is due to the old regex matching emphasis markers without any regard for whether they are `em` (single) or `strong` (double).
The new regex will only match markers that aren't preceded or followed by a similar marker

Fix `middle-word-em` extra preventing strongs from being recognized (#606)

---

CHANGES.md
lib/markdown2.py

This PR closes #608 by adding a CLI option to output to a file instead of stdout. Example usage:
```bash
python lib/markdown2.py text.md --output index.html
```

Add option to output to file in CLI (#608)

---

lib/markdown2.py

This PR refactors `_do_links`, simplifying it and removing alot of duplicated code.
The main point of duplication was around differences in processing inline images/anchors vs reference images and anchors. Both have different ways of extracting the key components of a link: URL, title and end index. However, once these are extracted, they are processed in exactly the same way.
The problem was, the processing code was duplicated across both branches of the if/else statement. This refactor fixes that.
Hopefully this simplification can lay the ground work for potential future improvements

Refactor `_do_links` and simplify link handling logic

---

CHANGES.md
lib/markdown2.py
test/tm-cases/footnotes_order_of_appearance.html

This PR follows up on a comment on #536 that shows that the footnote labels are appearing out-of-order, even though the footnote links themselves are accurate. This bug was due to the out-of-order processing of some markdown elements and the order of insertion into the `footnote_ids` list.
Example:
```
one [^1]
- two [^2]
[^1]: one
[^2]: two
```
The footnote label is inserted [as each footnote is processed](https://github.com/trentm/python-markdown2/blob/c2b74275ca3e9d839cf627f4e160396d6ea9fc88/lib/markdown2.py#L1587). However, the list is processed first, which means its footnote is processed firstthat it is given the label of `1` mistakenly.
This PR fixes that by instead inserting a placeholder here, and then postprocessing the entire text top-to-bottom, which fixes the labelling.

Fix footnote labels appearing out-of-order (#536)

---

lib/markdown2.py
test/tm-cases/tables.html
test/tm-cases/tables.text

fix: make tables without body gfm compatible

---

CHANGES.md
lib/markdown2.py
test/testall.py
test/tm-cases/fenced_code_blocks_issue426.html
test/tm-cases/fenced_code_blocks_syntax_indentation.html
test/tm-cases/markdown_file_links.html
test/tm-cases/markdown_file_links.opts
test/tm-cases/markdown_file_links.text
test/tm-cases/markdown_file_links_no_linkdefs.html
test/tm-cases/markdown_file_links_no_linkdefs.opts
test/tm-cases/markdown_file_links_no_linkdefs.text

This PR closes #528 by adding an extra that converts `.md` links to `.html` links. I've also spun the link processing logic out into a `LinkProcessor` extra, which can be subclassed and re-used just like the `ItalicAndBoldProcessor`.
This new extra contains all of the link processing logic, allowing new extras to piggy-back off of it and manipulate links without having to re-implement the syntax matching themselves.
The class allows subclasses to filter which links they wish to process (inline/reference and anchor/image).
Simply replaces `.md` links with `.html`. Also works for link definitions, although this can be turned off using the extra's options. EG: `markdown(..., extras={'markdown-file-links': {'link_defs': False}})`

Add `MarkdownFileLinks` extra (#528)

---

CHANGES.md
lib/markdown2.py
test/tm-cases/smarty_pants_issue620.html
test/tm-cases/smarty_pants_issue620.opts
test/tm-cases/smarty_pants_issue620.text

This PR fixes #620 by adding missing block tags to the block tags regex.
Smarty-pants was mangling quotes in the `video` element, which should be hashed by `_hash_html_blocks`, but `video` was missing from `_html5tags` and `_block_tags_a`. Adding it fixed this.
I also added a bunch of other block-level tags listed on [w3docs](https://www.w3docs.com/learn-html/html-block-and-inline-elements.html) such as `canvas`, `dd`, `dt` and `address`

Add missing block tags to regex (#620)

---

CHANGES.md
lib/markdown2.py
test/tm-cases/safe_mode_issue621.html
test/tm-cases/safe_mode_issue621.opts
test/tm-cases/safe_mode_issue621.text

This PR fixes #621 by changing `_html_escape_url` to no longer escape `+` characters.
As pointed out in #621, `+` [is a valid URL character](https://stackoverflow.com/a/7109208), and therefore shouldn't be escaped in URLs.
I'm not sure exactly why they were being escaped in the first place, although it seems the first usage comes from 000343d as part of #230:
```python
if safe_mode:
escaped = quote_plus(attr).replace('+', ' ')
```
[`quote_plus`](https://docs.python.org/3/library/urllib.parse.html#urllib.parse.quote_plus) replaces spaces with plus signs, and I'm guessing escapes some other characters too. They then go back and replace the plus signs with spaces again. Seems redundant and doesn't look like we need it

Don't escape plus signs in URLs (#621)

---

CHANGES.md
lib/markdown2.py
test/tm-cases/encode_incomplete_tags_xss_issue625.html
test/tm-cases/encode_incomplete_tags_xss_issue625.opts
test/tm-cases/encode_incomplete_tags_xss_issue625.text

This PR fixes #625 by doing a proper and thorough check for auto links in `_encode_incomplete_tags`.
The previous check was flimsy and could easily be tricked by some malicious HTML.

Fix XSS when encoding incomplete tags (#625)

---

CHANGES.md
lib/markdown2.py
test/tm-cases/middle_word_em_issue627.html
test/tm-cases/middle_word_em_issue627.opts
test/tm-cases/middle_word_em_issue627.text

This PR fixes #627, where if the extra options for `middle-word-em` was set to `None` it would raise a TypeError.
For extras, it's possible to initialise them without any options like so: `extras={'abc': None}`. This is usually handled in `Extra.__init__` and converted to an empty dictionary, so that the extras don't have to worry about a bunch of runtime type checks:
https://github.com/trentm/python-markdown2/blob/c91007d82f90f55800b69adc6298a75351e710af/lib/markdown2.py#L2382
However, middle-word-em would try to set some default options before calling `super().__init__`, and didn't have sufficient checks for if the value is None. This PR adds a check and converts it to a dict if so

Fix TypeError in MiddleWordEm extra when options was None (#627)

---

.github/workflows/python.yaml
CHANGES.md
Makefile
lib/markdown2.py
test/test_redos.py

This PR fixes #633, which showcases a ReDoS vulnerability in `_sorta_html_tokenize_re`. This PR also adds a regression test suite for ReDoS attacks and integrates it as part of the CICD checks.
The problem was with the section of regex that matches tags with attributes, specifically line 1276:
https://github.com/trentm/python-markdown2/blob/adf4e8199ec08ee2ade22eb80703cfb44decbbce/lib/markdown2.py#L1272-L1278
The problem was with the section that matches quoted attribute values using `".*?"`. Take the following input:
```
<p m="1"<p m="1"<p m="1"<p m="1"<p m="1"<p m="1"<p m="1" ...[x 5000]...         </div
```
The first `m="1"` matches the attribute regex just fine, but then we hit another `<p` right after. The regex expects a closing bracket for this tag, so it assumes this is part of …

Fix ReDoS in HTML tokenizer regex (#633)

---

CHANGES.md
lib/markdown2.py
test/tm-cases/code_friendly_issue638.html
test/tm-cases/code_friendly_issue638.opts
test/tm-cases/code_friendly_issue638.text

This PR fixes #638.
The issue was in the following snippet:
```md
a_b this should be **bold** c_d this is **bold**
```
Code friendly would recognise the text in-between the 2 underscores as a potential `<em>`. It would hash that entire section to protect it from being turned into an `<em>`, but this also prevented the contents of that substring from being processed, including the `<strong>` in the middle.
This is fixed by simply hashing the `_` characters instead, leaving the contents available to be processed as normal.

Fix code friendly preventing other syntax from being processed (#638)

---

CHANGES.md
lib/markdown2.py
test/markdowntest-cases/Strong and em together.html
test/tm-cases/consecutive_strong_and_em.html
test/tm-cases/consecutive_strong_and_em.text
test/tm-cases/ems_across_spans.html
test/tm-cases/ems_across_spans.text
test/tm-cases/middle_word_em_issue641.html
test/tm-cases/middle_word_em_issue641.opts
test/tm-cases/middle_word_em_issue641.text
test/tm-cases/middle_word_em_with_extra_ems.html

This PR fixes #641, fixes #642 and fixes #643.
I put all these fixes in the same PR because I wanted to make sure they were compatible with each other, but that does mean it's a bit messy.
The middle word em regex would check for `*_` chars that aren't preceded by another em char or a whitespace. The text `(*em*)` matches that, as the leading em char is not preceded by a space. It would then prevent this text from being processed as a valid em.
I've updated the regex to look for ems that aren't preceded by non-word chars (instead of whitespace) and that fixed this issue.
The result is that we process this as expected:
```html
(<em>em</em>)
```
In this issue we had what looked like an `<em>` span, but it was straddling two other `<strong>` spans:
```md
**_confusing** ident is …
```

Fix a number of em/strong issues (#641, #642, #643)
